### PR TITLE
laravel new project_name --git

### PR DESCRIPTION
**Pull request by Danysan1**
This merge request implements the feature request from https://github.com/laravel/installer/issues/224 .

If the `git` parameter is passed then `laravel new project_name --git` is called instead of `laravel new project_name`, initializing the git repository for the project (as documented in https://laravel.com/docs/9.x#the-laravel-installer ).

### CODE REVIEW

**Comment by driesvints** [comment]
So, I don't think this implementation can be used. You see, the sail installation process is run inside a Docker container rather than on your machine. That means git won't be configured properly. Shouldn't we run git on the host machine instead?

Did you actually try this out?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by Danysan1** [comment]
@driesvints yes, I ran `curl -s "http://localhost:8000/aaa?with=mysql,redis&devcontainer&git" | bash`, I saw that the initialization script completed and the Laravel project was created so I assumed it had completed everything... that was definitely a bad assumption! Sorry!

Running it again and looking better at the output it appears that, even if the script hasn't stopped, where it should do the `git init` it throws a warning... 
```
error: unknown option `no-ansi'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]
```
... due to [the `--no-ansi` parameter that `laravel new` adds](https://github.com/laravel/installer/blob/cbe83b68e88291fe1218b0d5c8fdb3361e146ee9/src/NewCommand.php#L359) and git does not recognize.

Also, you're right, even if `git init` had succeeded `git commit` would have stopped due to git being installed but not configured into the new container.

A possible alternative would be to do just a `laravel new project_name && git init -q && ...` instead of `laravel new project_name --git && ...` which would maintain the advantage of running inside the container (not requiring git on the host machine) at the cost of not committing. The other possible alternative would be to add at the end the commands  `git init -q && git add . && git commit -q -m "Set up a fresh Laravel Sail app"`, which would maintain the commit at the cost of requiring git on the host machine.

**Comment by driesvints** [comment]
@Danysan1 it seems Taylor doesn't wants this right now so I think it's best to leave things be. Thanks and sorry

**Pull request closed without merging**
